language: ruby
rvm:
  - 1.9.3
script: bundle exec rspec spec
before_script:
  - psql -c 'create database labrats_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - rake db:migrate
  - rake db:test:prepare
